{% set name = "trulens-feedback" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: db5564acc7ca2526d8d89573dca950c5e41e6cc689283d834268fac7be93597c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.1
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.12
    - trulens-core >=1.0.0,<2.0.0
    - nltk >=3.9.1,<4.0.0
    - pydantic >=2.0.0,<3.0.0
    - numpy >=1.23.0,<2.0.0
    - scikit-learn >=1.3.0,<2
    - scipy >=1.10.1,<2
    - requests >=2.31.0,<3.0.0
test:
  imports:
    - trulens.feedback
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: A TruLens extension package implementing feedback functions for LLM App evaluation.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
