{% set name = "trulens-providers-cortex" %}
{% set pyname = name.replace('-', '.') %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% if environ.get('CONDA_SOURCE_USE_PATH') == '1' %}
  path: ./
  {% else %}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-providers-cortex/#files
  sha256: 9374299fb4bf35c625a588f59f8d3f8c53b8a88cffbe215fb07163fcc1a41c3c
  {% endif %}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - trulens-core >=1.0.0,<3.0.0
    - trulens-feedback >=1.0.0,<3.0.0
    - packaging >=23.0
    - snowflake-connector-python >=3.11.0,<4.0.0
    - snowflake-ml-python >=1.7.2,<2.0.0
    - snowflake-snowpark-python >=1.18.0,<2.0.0

test:
  imports:
    - {{ pyname }}
  commands:
    - pip check
    - python -c 'import {{ pyname }}; assert {{ pyname }}.__version__ == "{{ version }}", "Installed version does not match expected version"'
  requires:
    - python >=3.9,<3.13
    - pip

about:
  home: https://trulens.org/
  summary: A TruLens extension package adding Snowflake Cortex support for LLM App evaluation.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
