# This a definition for azure pipelines, not github pipelines. There are
# differences between these systems.

trigger: none

pr:
  # Run this pipeline for any PR that wishes to push to main that changes code
  # inside docs folder, notebooks, or this pipeline definition itself.
  branches:
    include:
      - main
  paths:
    include:
      - docs
      - examples
      - mkdocs.yml
      - .azure_pipelines/ci-docs-pr.yaml

jobs:
  - job: DocsCheck
    displayName: "Check Documentation"
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        latest:
          # Snowflake libraries are not available on >=3.12.
          python-version: "3.11"

    steps:
      - template: templates/env-setup.yaml

      - bash: |
          poetry install --only dev --sync
          make run-precommit
        displayName: "Run pre-commit hooks (format + nb-clean)"

      - bash: |
          poetry install --with docs --sync
          make docs-linkcheck-strict
        displayName: "Build docs and check for broken links"
