trigger: none

pr:
  branches:
    include:
      - main

jobs:
- template: templates/run-unit-tests-for-python-version.yaml
  parameters:
    pythonVersion: "3.9"
- template: templates/run-unit-tests-for-python-version.yaml
  parameters:
    pythonVersion: "3.10"
- template: templates/run-unit-tests-for-python-version.yaml
  parameters:
    pythonVersion: "3.11"
- template: templates/run-unit-tests-for-python-version.yaml
  parameters:
    pythonVersion: "3.12"
- template: templates/build-conda-packages.yaml
  parameters:
    pythonVersion: "3.11"
