# This a definition for azure pipelines, not github pipelines. There are
# differences between these systems.

trigger: none

pr:
  branches:
    include:
      - main

jobs:
  - job: PRBranchProtect # name seems to be important but cannot figure out why
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 30

    strategy:
      matrix:
        default: # name is important
          python-version: 3.12
        py309-static:
          python-version: 3.9
        py310-static:
          python-version: 3.10
        py311-static:
          python-version: 3.11

    steps:
      - template: templates/env-setup.yaml
      - template: templates/run-precommits.yaml
      - template: templates/run-tests.yaml
        parameters:
          testSuite: unit
      - template: templates/run-optional-tests.yaml
        parameters:
          testSuite: unit
