trigger: none

pr:
  # Run this pipeline for any PR from a branch that starts with "releases/" that
  # changed code in trulens_eval folder or to eval notebooks in the docs folder.
  branches:
    include:
      - releases/*
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

# schedules:
#  - cron: "0 0 * * *"
#    displayName: Daily midnight build
#    branches:
#      include:
#        - main

jobs:
  - job: ReleaseTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        latest:
          pythonVersion: "3.11"
          condaEnvFileSuffix: "trulens-llm"


    steps:
      - checkout: self
        clean: true

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: |
          set -e
          conda create  -y --quiet -n $(condaEnvFileSuffix) python=3.11
          conda init bash
        displayName: Create Anaconda environment

      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          which python
          python --version
        displayName: Which Python

      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          pip install -r requirements.dev.txt

          cd ./trulens_eval
          pip install -e .
          pip install -r tests/docs_notebooks/requirements.txt
          pip install ipykernel
          python -m ipykernel install --user --name $(condaEnvFileSuffix) --display-name $(condaEnvFileSuffix)
        displayName: Install pip package

      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          pre-commit run --all-files --show-diff-on-failure
        displayName: Format Code

      - bash: |
          source activate $(condaEnvFileSuffix)
          cd ./docs/trulens_eval
          pip install jupyter
        displayName: Install jupyter

      - bash: |
          source activate $(condaEnvFileSuffix)

          cd ./trulens_eval
          pip install pytest==7.0.1 pytest-azurepipelines
          pip install -r trulens_eval/requirements.optional.txt
        displayName: Install optional deps

      - bash: |
          source activate $(condaEnvFileSuffix)
          echo "$(python --version)"
          echo "$(pip list)"
        displayName: Pip list

      - bash: |
          source activate $(condaEnvFileSuffix)
          cd ./trulens_eval

          python -m pytest tests/e2e

        displayName: Run e2e tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)

      - bash: |
          source activate $(condaEnvFileSuffix)
          cd ./trulens_eval

          python -m pytest tests/docs_notebooks

        displayName: Run notebook tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)
