trigger:
  branches:
    include:
      - main
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb

pr:
  branches:
    include:
      - releases/*
  paths:
    include:
      - trulens_eval
      - docs/trulens_eval/*.ipynb


jobs:
  - job: quickstartTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        docs_notebooks:
          condaEnvFileSuffix: "trulens-llm"
          requirementsFile: "tests/docs_notebooks/requirements.txt"
          testSubdirectory: "tests/docs_notebooks"

    steps:
      - checkout: self
        clean: true
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: |
          set -e
          conda create  -y --quiet -n $(condaEnvFileSuffix) python=3
          conda init bash
        displayName: Create Anaconda environment
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          which python
        displayName: Which Python
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          cd ./trulens_eval
          pip install -e .
          pip install -r $(requirementsFile)
          pip install yapf==0.32.0
          pip install isort==5.10.1
          pip install ipykernel
          python -m ipykernel install --user --name $(condaEnvFileSuffix) --display-name $(condaEnvFileSuffix)
        displayName: Install pip package
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          ./format.sh
        displayName: Format Code
      - bash: |
          num_changed_files=`git ls-files --others -m --exclude-standard | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi
        displayName: NoDiffCheck
      - bash: |
          source activate $(condaEnvFileSuffix)
          cd ./docs/trulens_eval
          pip install jupyter
          pip install nbmerge
          ../../.github/workflows/combine_nb_to_docs_testing.sh
        displayName: Run combine docs for testing
      - bash: |
          source activate $(condaEnvFileSuffix)
          pip install pytest==7.0.1 pytest-azurepipelines langchain>=0.0.170 llama_index>=0.6.24 
          pip install docarray hnswlib
          echo '::group::piplist'
          echo "$(pip list)"
          echo '::endgroup::'
          cd ./trulens_eval
          python -m pytest $(testSubdirectory)
        displayName: Run unit tests
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)
          HUGGINGFACE_API_KEY: $(HUGGINGFACE_API_KEY)
          PINECONE_API_KEY: $(PINECONE_API_KEY)
          PINECONE_ENV: $(PINECONE_ENV)
          HUGGINGFACEHUB_API_TOKEN: $(HUGGINGFACEHUB_API_TOKEN)
