trigger:
  branches:
    include:
      - main
  paths:
    include:
      - trulens_explain

pr:
  branches:
    include:
      - main
      - releases/*
  paths:
    include:
      - trulens_explain
jobs:
  - job: lensApiTests
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    strategy:
      matrix:
        py38_tf1_keras:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/keras/requirements_tfv1.txt"
          testSubdirectory: "tests/keras"

        py38_tf1_tf_keras:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/tf_keras/requirements_tfv1.txt"
          testSubdirectory: "tests/tf_keras"

        py38_pytorch:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/pytorch/requirements.txt"
          testSubdirectory: "tests/pytorch"

        py38_tf1:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/tf/requirements.txt"
          testSubdirectory: "tests/tf"

        py38_tf2:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/tf2/requirements.txt"
          testSubdirectory: "tests/tf2"

        py38_tf2_non_eager:
          condaEnvFileSuffix: "python38"
          requirementsFile: "tests/tf2/requirements.txt"
          testSubdirectory: "tests/tf2_non_eager"

        py3_10_notebooks:
          condaEnvFileSuffix: "python3_10"
          requirementsFile: "tests/notebooks/requirements.txt"
          testSubdirectory: "tests/notebooks"

        py3_10_notebooks_latest:
          condaEnvFileSuffix: "python3_10"
          requirementsFile: "tests/notebooks/requirements_latest.txt"
          testSubdirectory: "tests/notebooks"

    steps:
      - checkout: self
        clean: true
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - bash: |
          set -e
          CONDA_FILENAME=$(condaEnvFileSuffix)
          CONDA_YAML="trulens_explain/tools/conda_${CONDA_FILENAME}.yaml"
          echo $CONDA
          conda env create --force --quiet --file $CONDA_YAML
          conda init bash
        displayName: Create Anaconda environment
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          which python
          python --version
        displayName: Which Python
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          pip install pyzmq!=24.0.0 # CI/CD Broken on this version
          pip install ipykernel
          cd ./trulens_explain
          pip install -r $(requirementsFile)
          python -m ipykernel install --user --name $(condaEnvFileSuffix) --display-name "$(condaEnvFileSuffix)"
        displayName: Install pip package
      - bash: |
          set -e
          source activate $(condaEnvFileSuffix)
          echo Using $(yapf --version) isort $(isort --vn)
          ./format.sh --explain
        displayName: Format Code
      - bash: |
          num_changed_files=`git ls-files --others -m --exclude-standard ./trulens_explain | wc -l`
          if [ $num_changed_files -ne 0 ]; then
            echo "The following files have changed after running format.sh. Please format your code and update the PR."
            git ls-files --others -m --exclude-standard ./trulens_explain
            echo "\n\nOutputting git diff for checked in files.\n"
            git diff
          fi
        displayName: NoDiffCheck
      - bash: |
          source activate $(condaEnvFileSuffix)
          pip install pytest==7.0.1 pytest-azurepipelines
          cd ./trulens_explain
          python -m pytest $(testSubdirectory)
        displayName: Run unit tests
