# conda metadata build recipe

{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}
{% set name = poetry.get('name') %}
{% set version = poetry.get('version') %}

{% set core_pyproject = load_file_data('../src/core/pyproject.toml', from_recipe_dir=True) %}
{% set core_poetry = core_pyproject.get('tool', {}).get('poetry') %}
{% set core_name = core_poetry.get('name') %}
{% set core_version = core_poetry.get('version') %}

{% set feedback_pyproject = load_file_data('../src/feedback/pyproject.toml', from_recipe_dir=True) %}
{% set feedback_poetry = feedback_pyproject.get('tool', {}).get('poetry') %}
{% set feedback_name = feedback_poetry.get('name') %}
{% set feedback_version = feedback_poetry.get('version') %}

{% set cortex_pyproject = load_file_data('../src/providers/cortex/pyproject.toml', from_recipe_dir=True) %}
{% set cortex_poetry = cortex_pyproject.get('tool', {}).get('poetry') %}
{% set cortex_name = cortex_poetry.get('name') %}
{% set cortex_version = cortex_poetry.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vvv

outputs:
  - name: {{ core_name|lower }}
    version: {{ core_version }}
    source:
      url: https://pypi.io/packages/source/{{ core_name[0] }}/{{ core_name }}/{{ core_name }}-{{ core_version }}.tar.gz
    build:
      noarch: python
      number: 0
      script: python -m pip install . --no-deps --ignore-installed -vvv
  - name: {{ feedback_name|lower }}
    version: {{ feedback_version }}
    source:
      url: https://pypi.io/packages/source/{{ feedback_name[0] }}/{{ feedback_name }}/{{ feedback_name }}-{{ feedback_version }}.tar.gz
    build:
      noarch: python
      number: 0
      script: python -m pip install . --no-deps --ignore-installed -vvv
  - name: {{ cortex_name|lower }}
    version: {{ cortex_version }}
    source:
      url: https://pypi.io/packages/source/{{ cortex_name[0] }}/{{ cortex_name }}/{{ cortex_name }}-{{ cortex_version }}.tar.gz
    build:
      noarch: python
      number: 0
      script: python -m pip install . --no-deps --ignore-installed -vvv
