#!/usr/bin/env python3
"""Fix indentation issues in notebook Metric() calls generated by the migration script.

The migration script produced Metric() calls with flat 4-space indentation
inside parenthesized expressions like:

    f_groundedness = (
        Metric(
    implementation=...,      <-- wrong: should be 8-space indent
    name=...,
    selectors={
        "source": ...,       <-- wrong: should be 12-space indent
    },
)                            <-- wrong: should be 4-space indent
    )

This script fixes them to:

    f_groundedness = Metric(
        implementation=...,
        name=...,
        selectors={
            "source": ...,
        },
    )
"""

import json
import os
import re
import sys

COOKBOOK_DIR = os.path.join(os.path.dirname(__file__), "docs", "cookbook")


def fix_metric_indentation(source_str: str) -> str:
    """Fix indentation of Metric() calls in a source string."""
    lines = source_str.split("\n")
    new_lines = []
    i = 0
    changed = False

    while i < len(lines):
        line = lines[i]

        # Pattern 1: variable = (\n    Metric(\n    implementation=...
        # Fix by removing the outer parens and fixing indentation
        # Detect: "varname = (\n"
        m_open = re.match(r'^(\s*)([\w.]+\s*=\s*)\(\s*$', line)
        if m_open:
            base_indent = m_open.group(1)
            var_assign = m_open.group(2)

            # Look ahead: next line should be base_indent + "    Metric("
            if i + 1 < len(lines):
                next_line = lines[i + 1]
                m_metric = re.match(r'^(\s*)Metric\(\s*$', next_line)
                if m_metric:
                    metric_indent = m_metric.group(1)
                    # This is the pattern we need to fix
                    # Collect all lines until we find the matching close paren
                    # The Metric() block ends with ")" at metric_indent level
                    # Then there should be a ")" at base_indent + "    " level

                    # Rewrite: "varname = Metric(" then indent inner by base+4
                    metric_lines = []
                    j = i + 2  # skip the "var = (" and "    Metric(" lines

                    # Find the closing ")" of Metric(
                    depth = 1
                    while j < len(lines) and depth > 0:
                        l = lines[j]
                        stripped = l.strip()
                        # Count parens (rough)
                        for c in stripped:
                            if c == '(':
                                depth += 1
                            elif c == ')':
                                depth -= 1
                                if depth == 0:
                                    break
                        if depth > 0:
                            metric_lines.append(l)
                            j += 1
                        else:
                            # This line has the closing ) of Metric
                            # It might also have trailing content like "  # comment"
                            # The line is something like ")" or ")  # comment"
                            metric_close_line = lines[j]
                            j += 1
                            break

                    # Now check if next line is the outer ")"
                    outer_close = None
                    if j < len(lines):
                        outer_stripped = lines[j].strip()
                        if outer_stripped == ")" or outer_stripped.startswith(")"):
                            outer_close = j
                            j += 1

                    if outer_close is not None:
                        # Rewrite the block
                        # Extract any trailing comment from metric close line
                        close_stripped = metric_close_line.strip()
                        trailing = ""
                        if close_stripped.startswith(")") and len(close_stripped) > 1:
                            trailing = close_stripped[1:].strip()
                            if trailing:
                                trailing = "  " + trailing

                        new_lines.append(f"{base_indent}{var_assign}Metric(")

                        # Re-indent metric inner lines
                        for ml in metric_lines:
                            # Determine original indent and re-base
                            orig_stripped = ml.lstrip()
                            orig_indent_len = len(ml) - len(orig_stripped)

                            # The original lines had flat indentation (4 spaces per level)
                            # We need to re-indent relative to base_indent + 4
                            new_indent = base_indent + "    " + " " * orig_indent_len
                            # Actually, let's be smarter: detect the min indent of the block
                            # and re-base from there
                            pass

                        # Simpler approach: calculate what indent the inner lines should have
                        # Inner args of Metric() should be at base_indent + 4
                        # Nested dict contents at base_indent + 8
                        # etc.

                        # Find the minimum indentation of the metric_lines
                        min_indent = float('inf')
                        for ml in metric_lines:
                            if ml.strip():
                                min_indent = min(min_indent, len(ml) - len(ml.lstrip()))
                        if min_indent == float('inf'):
                            min_indent = 0

                        target_base = len(base_indent) + 4
                        for ml in metric_lines:
                            if not ml.strip():
                                new_lines.append("")
                            else:
                                orig_indent_len = len(ml) - len(ml.lstrip())
                                relative = orig_indent_len - min_indent
                                new_indent = " " * (target_base + relative)
                                new_lines.append(new_indent + ml.lstrip())

                        new_lines.append(f"{base_indent}){trailing}")
                        changed = True
                        i = j
                        continue

        # Pattern 2: Metric() with args at wrong indent (not inside parens)
        # e.g., "f_x = Metric(\nimplementation=...\n)" where inner content lacks indent
        m_direct = re.match(r'^(\s*)([\w.]+\s*=\s*)Metric\(\s*$', line)
        if m_direct:
            base_indent = m_direct.group(1)
            var_assign = m_direct.group(2)
            target_indent = base_indent + "    "

            # Check if next line's indentation is less than expected
            if i + 1 < len(lines) and lines[i + 1].strip():
                next_indent = len(lines[i + 1]) - len(lines[i + 1].lstrip())
                expected = len(target_indent)
                if next_indent < expected and lines[i + 1].strip() not in (")", "),"):
                    # Need to re-indent the block
                    new_lines.append(line)
                    j = i + 1
                    depth = 1

                    # Find min indent of the block
                    block_lines = []
                    k = j
                    d = 1
                    while k < len(lines) and d > 0:
                        l = lines[k]
                        for c in l:
                            if c == '(':
                                d += 1
                            elif c == ')':
                                d -= 1
                                if d == 0:
                                    break
                        if d > 0:
                            block_lines.append(l)
                        else:
                            block_lines.append(l)  # closing line
                        k += 1

                    min_indent_val = float('inf')
                    for bl in block_lines[:-1]:  # exclude closing line
                        if bl.strip():
                            min_indent_val = min(min_indent_val, len(bl) - len(bl.lstrip()))
                    if min_indent_val == float('inf'):
                        min_indent_val = 0

                    if min_indent_val < expected:
                        for idx, bl in enumerate(block_lines):
                            if not bl.strip():
                                new_lines.append("")
                            elif idx == len(block_lines) - 1:
                                # Closing line
                                close_stripped = bl.strip()
                                new_lines.append(base_indent + close_stripped)
                            else:
                                orig_indent_len = len(bl) - len(bl.lstrip())
                                relative = orig_indent_len - min_indent_val
                                new_indent = " " * (expected + relative)
                                new_lines.append(new_indent + bl.lstrip())
                        changed = True
                        i = k
                        continue

        new_lines.append(line)
        i += 1

    return "\n".join(new_lines), changed


def fix_redundant_selector_import(source_str: str) -> str:
    """Remove redundant 'from trulens.core.feedback.selector import Selector' 
    when 'from trulens.core import Metric, Selector' already exists."""
    lines = source_str.split("\n")
    has_core_selector = False
    has_separate_selector = False
    separate_idx = None

    for idx, line in enumerate(lines):
        stripped = line.strip()
        if re.match(r'from trulens\.core import.*Selector', stripped):
            has_core_selector = True
        if stripped == "from trulens.core.feedback.selector import Selector":
            has_separate_selector = True
            separate_idx = idx

    if has_core_selector and has_separate_selector and separate_idx is not None:
        lines.pop(separate_idx)
        # Remove trailing blank line if it created a double blank
        if separate_idx < len(lines) and separate_idx > 0:
            if lines[separate_idx - 1].strip() == "" and separate_idx < len(lines) and lines[separate_idx].strip() == "":
                lines.pop(separate_idx)
        return "\n".join(lines), True

    return source_str, False


def process_notebook(fpath):
    """Process a .ipynb file."""
    with open(fpath, "r") as f:
        nb = json.load(f)

    file_changed = False
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        source_lines = cell.get("source", [])
        source_str = "".join(source_lines)

        if "Metric(" not in source_str and "from trulens.core.feedback.selector import Selector" not in source_str:
            continue

        new_source = source_str
        changed = False

        # Fix indentation
        new_source, c1 = fix_metric_indentation(new_source)
        changed = changed or c1

        # Fix redundant imports
        new_source, c2 = fix_redundant_selector_import(new_source)
        changed = changed or c2

        if changed:
            new_lines = []
            for line in new_source.split("\n"):
                new_lines.append(line + "\n")
            if new_lines and source_lines and not source_lines[-1].endswith("\n"):
                new_lines[-1] = new_lines[-1].rstrip("\n")
            cell["source"] = new_lines
            file_changed = True

    if file_changed:
        with open(fpath, "w") as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)
            f.write("\n")

    return file_changed


def process_py_file(fpath):
    """Process a .py file."""
    with open(fpath, "r") as f:
        source = f.read()

    new_source = source
    changed = False

    new_source, c1 = fix_metric_indentation(new_source)
    changed = changed or c1

    new_source, c2 = fix_redundant_selector_import(new_source)
    changed = changed or c2

    if changed:
        with open(fpath, "w") as f:
            f.write(new_source)

    return changed


def main():
    files = []
    for dirpath, _, filenames in os.walk(COOKBOOK_DIR):
        for fn in filenames:
            if fn.endswith((".ipynb", ".py")):
                fpath = os.path.join(dirpath, fn)
                with open(fpath, "r") as f:
                    content = f.read()
                if "Metric(" in content or "from trulens.core.feedback.selector import Selector" in content:
                    files.append(fpath)

    print(f"Found {len(files)} files to check")
    changed = []
    for fpath in sorted(files):
        rel = os.path.relpath(fpath, os.path.dirname(__file__))
        try:
            if fpath.endswith(".ipynb"):
                if process_notebook(fpath):
                    changed.append(rel)
                    print(f"  FIXED: {rel}")
            elif fpath.endswith(".py"):
                if process_py_file(fpath):
                    changed.append(rel)
                    print(f"  FIXED: {rel}")
        except Exception as e:
            print(f"  ERROR: {rel} - {e}")

    print(f"\nFixed {len(changed)} files")
    return changed


if __name__ == "__main__":
    main()
