line-length = 80
include = [
  "trulens_eval/**/*.py",
  "trulens_eval/**/*.pyi",
  "trulens_eval/**/*.ipynb"
]

[lint]
preview = true
ignore = [
  "E731",
]
extend-select = [
  "I",
  "E303",
]

[lint.isort]
force-single-line = true
force-sort-within-sections = true
single-line-exclusions = [
  "typing",
]
known-first-party = [
  "trulens_eval",
  "tests",
  "examples",
]

[lint.pydocstyle]
convention = "google"
