parameters:
  - name: pythonVersion
    type: string
    values:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"

jobs:
- job: BuildCondaPackages
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 30
  steps:
  - template: env-setup.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
  - bash: |
      set -e
      conda install conda-build
    displayName: Install conda-build
  - bash: |
      set -e
      cd ./src/otel/semconv/
      conda build .
    displayName: Build `trulens-otel-semconv`
  - bash: |
      set -e
      cd ./src/core
      conda build .
    displayName: Build `trulens-core`
  - bash: |
      set -e
      cd ./src/feedback
      conda build .
    displayName: Build `trulens-feedback`
  - bash: |
      set -e
      cd ./src/dashboard
      conda build .
    displayName: Build `trulens-dashboard`
  - bash: |
      set -e
      cd ./src/connectors/snowflake
      conda build .
    displayName: Build `trulens-connectors-snowflake`
  - bash: |
      set -e
      cd ./src/providers/cortex
      conda build .
    displayName: Build `trulens-providers-cortex`
