parameters:
  - name: python-version
    type: string
    values:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"

jobs:
- job: RunAllUnitTests
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 30
  steps:
  - template: templates/env-setup.yaml
  - template: templates/run-precommits.yaml
  - template: templates/run-tests.yaml
    parameters:
      pytestMarker: basic
      testSuite: unit
  - template: templates/run-tests.yaml
    parameters:
      pytestMarker: optional
      testSuite: unit
  - template: templates/run-tests.yaml
    parameters:
      pytestMarker: snowflake
      testSuite: unit
