parameters:
  - name: pythonVersion
    type: string
    values:
      - "3.9"
      - "3.10"
      - "3.11"
      - "3.12"

jobs:
- job: RunAllUnitTestsForPython${{ replace(parameters.pythonVersion, '.', '') }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 30
  steps:
  - template: env-setup.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
  - template: run-precommits.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
  - template: run-tests.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      pytestMarker: basic
      testSuite: unit
  - template: run-tests.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      pytestMarker: optional
      testSuite: unit
  - template: run-tests.yaml
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      pytestMarker: snowflake
      testSuite: unit
