{% set name = "trulens-otel-semconv" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Replace url and sha256 with below line to test build locally with `conda build . -c https://conda.anaconda.org/sfe1ed40/``
  # path: .
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-otel-semconv/#files
  sha256: 13ac988a43b3b7ce00ebbcfa5f90d8e40775c64a005d53f7addeaa63640ae860

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.12
    - opentelemetry-semantic-conventions >=0.36b0

test:
  imports:
    - trulens.otel.semconv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
