{% set name = "trulens-core" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-core/#files
  sha256: 7d7627d594ac540e4be55e714f81e23e9fcb62d649a3532d98ccb908a60b2893

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.12
    - trulens-otel-semconv >=1.0.0,<2.0.0
    - opentelemetry-api >=1.0.0,<2.0.0
    - opentelemetry-sdk >=1.0.0,<2.0.0
    - opentelemetry-proto >=1.0.0,<2.0.0
    - numpy >=1.23
    - munch >=2.5.0,<3.0.0
    - dill >=0.3.8,<0.4.0
    - typing_extensions >=4.9.0,<5.0.0
    - pydantic >=2.0.0,<3.0.0
    - pandas >=1.0.0,<3.0.0
    - rich >=13.6.0,<14.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - alembic >=1.8.1,<2.0.0
    - nest-asyncio >=1.5.0,<2.0.0
    - python-dotenv >=0.21,<2.0
    - requests >=2.31.0,<3.0.0
    - packaging >=23.0
    - importlib-resources >=6.0.0
  run_constrained:
    - tqdm >=4.2.0
    - openai >=1.0.0
    - httpx >=0.27

test:
  imports:
    - trulens.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
