{% set name = "trulens-apps-langgraph" %}
{% set pyname = name.replace('-', '.') %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Replace url and sha256 with below line to test build locally with `conda build . -c https://conda.anaconda.org/sfe1ed40/``
  # path: .
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-apps-langgraph/#files
  sha256: fcf4d13e7d3cc9ce2d91e6435dd29f21a1d9a4bbe9666dd62cba717fba32bfb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - trulens-core >=1.0.0,<3.0.0
    - trulens-apps-langchain >=1.0.0
    - pydantic >=2.4.2

test:
  imports:
    - {{ pyname }}
  commands:
    - pip check
    - python -c 'import {{ pyname }}; assert {{ pyname }}.__version__ == "{{ version }}", "Installed version does not match expected version"'
  requires:
    - python >=3.9,<3.13
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-dhuang
