"""create event table

Revision ID: 10
Revises: 9
Create Date: 2024-12-11 09:32:48.976169
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "10"
down_revision = "9"
branch_labels = None
depends_on = None


def upgrade(config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # TODO: The automatically generated code below likely references
    #       tables such as "trulens_feedback_defs" or "trulens_records".
    #       However, the common prefix for these tables "trulens_" is
    #       actually configurable and so replace it with the variable
    #       prefix.
    #       e.g. replace "trulens_records" with prefix + "records".
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trulens_events",
        sa.Column("event_id", sa.VARCHAR(length=256), nullable=False),
        sa.Column("record", sa.Text(), nullable=False),
        sa.Column("record_attributes", sa.Text(), nullable=False),
        sa.Column("record_type", sa.VARCHAR(length=256), nullable=False),
        sa.Column("resource_attributes", sa.Text(), nullable=False),
        sa.Column("start_timestamp", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("trace", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade(config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # TODO: The automatically generated code below likely references
    #       tables such as "trulens_feedback_defs" or "trulens_records".
    #       However, the common prefix for these tables "trulens_" is
    #       actually configurable and so replace it with the variable
    #       prefix.
    #       e.g. replace "trulens_records" with prefix + "records".
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trulens_events")
    # ### end Alembic commands ###
