"""set feedback function id to not nullable.

Revision ID: 2
Revises: 1
Create Date: 2024-08-10 23:11:37.405982
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2"
down_revision = "1"
branch_labels = None
depends_on = "1"


def upgrade(config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(prefix + "feedbacks") as batch_op:
        batch_op.alter_column(
            "feedback_definition_id",
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade(config) -> None:
    prefix = config.get_main_option("trulens.prefix")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(prefix + "feedbacks") as batch_op:
        batch_op.alter_column(
            "feedback_definition_id",
            nullable=True,
        )
    # ### end Alembic commands ###
