"""rename apps table to versions table

Revision ID: 3
Revises: 2
Create Date: 2024-08-08 19:19:42.092436

"""

from alembic import op
from alembic.config import Config

# revision identifiers, used by Alembic.
revision = "3"
down_revision = "2"
branch_labels = None
depends_on = "1"


def upgrade(config: Config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # TODO: need to prepend prefix to all table names in the upgrades
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(prefix + "apps", prefix + "versions")
    # ### end Alembic commands ###


def downgrade(config: Config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(prefix + "versions", prefix + "apps")
    # ### end Alembic commands ###
