"""rename app_id to version_tag

Revision ID: 4
Revises: 3
Create Date: 2024-08-08 19:19:42.092436

"""

from alembic import op
from alembic.config import Config

# revision identifiers, used by Alembic.
revision = "4"
down_revision = "3"
branch_labels = None
depends_on = "3"


def upgrade(config: Config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # TODO: need to prepend prefix to all table names in the upgrades
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        prefix + "versions",
        "app_id",
        new_column_name="app_version",
    )

    op.alter_column(
        prefix + "records",
        "app_id",
        new_column_name="app_version",
    )
    # ### end Alembic commands ###


def downgrade(config: Config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # TODO: need to prepend prefix to all table names in the upgrades
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        prefix + "apps",
        "app_version",
        new_column_name="app_id",
    )
    op.alter_column(
        prefix + "records",
        "app_version",
        new_column_name="app_id",
    )
    # ### end Alembic commands ###
