"""add app name and version fields

Revision ID: 7
Revises: 6
Create Date: 2024-08-27 11:09:26
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7"
down_revision = "6"
branch_labels = None
depends_on = "6"


def upgrade(config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        prefix + "apps",
        "app_name",
        existing_nullable=False,
        nullable=True,
    )
    op.alter_column(
        prefix + "apps",
        "app_version",
        existing_nullable=False,
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade(config) -> None:
    prefix = config.get_main_option("trulens.table_prefix")

    if prefix is None:
        raise RuntimeError("trulens.table_prefix is not set")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        prefix + "apps",
        "app_name",
        existing_nullable=True,
        nullable=False,
    )
    op.alter_column(
        prefix + "apps",
        "app_version",
        existing_nullable=True,
        nullable=False,
    )
    # ### end Alembic commands ###
