# conda metadata build recipe

{% set pyproject = load_file_data('../../src/core/pyproject.toml', from_recipe_dir=True) %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}
{% set name = poetry.get('name') %}
{% set version = poetry.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../src/core
  {# url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz #}
  {# sha256: 3d262120d24f62d75c197f13ef42465583e5c4b6340316a904be659803912c80 #}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<=3.11
    - pip ==24.0.0
    - poetry ==1.4.0
    - numpy >=1.23,<2
  run:
    - python >=3.9,<=3.11
    - pandas >=2.1,<3
    - rich >=13.6,<14
    - numpy >=1.23,<2
    - munch >=2.5,<3
    - dill >=0.3.8,<0.4
    - typing_extensions >=4.9,<5
    - pydantic >=2,<3
    - sqlalchemy >=2.0,<3
    - alembic >=1.8.1,<2
    - nest-asyncio >=1.5,<2
    - python-dotenv >=0.21.0
    - snowflake-connector-python >=3.11,<4
    - snowflake-snowpark-python >=1.20,<2

test:
  imports:
    - trulens.core
  commands:
    - pip check
  requires:
    - pip
