{% set name = "trulens-connectors-snowflake" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% if environ.get('CONDA_SOURCE_USE_PATH') == '1' %}
  path: ./
  {% else %}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-connectors-snowflake/#files
  sha256: 80995618e00af582c9c8fa2a7c30253e0d25093ffca26e19c135cda50d12ac6f
  {% endif %}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.12
    - trulens-core >=1.0.0,<2.0.0
    - snowflake-snowpark-python >=1.18.0,<2.0.0
    - snowflake-sqlalchemy >=1.6.0,<2.0.0

test:
  imports:
    - trulens.connectors.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
