{% set name = "trulens-connectors-snowflake" %}
{% set pyname = name.replace('-', '.') %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% if environ.get('CONDA_SOURCE_USE_PATH') == '1' %}
  path: ./
  {% else %}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  # Get SHA256 from https://pypi.org/project/trulens-connectors-snowflake/#files
  sha256: fe43adc59124b7a7376935de8c52959979d84a446f7b7fc4e0fd4d3f5d0a27d1
  {% endif %}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core <2.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - trulens-core >=1.0.0,<3.0.0
    - snowflake-snowpark-python >=1.18.0,<2.0.0
    - snowflake-sqlalchemy >=1.6.0,<2.0.0

test:
  imports:
    - {{ pyname }}
  commands:
    - pip check
    - python -c 'import {{ pyname }}; assert {{ pyname }}.__version__ == "{{ version }}", "Installed version does not match expected version"'
  requires:
    - python >=3.9,<3.13
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
