{% set name = "trulens-connectors-snowflake" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: afe145e90144de38598a48de8893a27aefafde2865079ef6fba6a81308e2b0e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.12
    - trulens-core >=1.0.0,<2.0.0
    - snowflake-snowpark-python >=1.18.0,<2.0.0
    - snowflake-sqlalchemy >=1.6.0,<2.0.0

test:
  imports:
    - trulens.connectors.snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trulens.org/
  summary: Library to systematically track and evaluate LLM based applications.
  license: MIT

extra:
  recipe-maintainers:
    - sfc-gh-srudenko
    - sfc-gh-chu
